[package]
name = "depressing_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
pretty_env_logger = "0.4"
log = "0.4"
chrono = "0.4"